[2023-09-28T17:43:31.781+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_processing.set_search_path scheduled__2023-09-27T00:00:00+00:00 [queued]>
[2023-09-28T17:43:31.791+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_processing.set_search_path scheduled__2023-09-27T00:00:00+00:00 [queued]>
[2023-09-28T17:43:31.791+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-09-28T17:43:31.804+0000] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): set_search_path> on 2023-09-27 00:00:00+00:00
[2023-09-28T17:43:31.809+0000] {standard_task_runner.py:57} INFO - Started process 74 to run task
[2023-09-28T17:43:31.813+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'set_search_path', 'scheduled__2023-09-27T00:00:00+00:00', '--job-id', '319', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp5cdzcuwd']
[2023-09-28T17:43:31.818+0000] {standard_task_runner.py:85} INFO - Job 319: Subtask set_search_path
[2023-09-28T17:43:32.055+0000] {task_command.py:410} INFO - Running <TaskInstance: user_processing.set_search_path scheduled__2023-09-27T00:00:00+00:00 [running]> on host 832d4089b5aa
[2023-09-28T17:43:32.209+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='user_processing' AIRFLOW_CTX_TASK_ID='set_search_path' AIRFLOW_CTX_EXECUTION_DATE='2023-09-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-27T00:00:00+00:00'
[2023-09-28T17:43:32.210+0000] {sql.py:265} INFO - Executing: SET search_path TO ***_ini
[2023-09-28T17:43:32.226+0000] {base.py:73} INFO - Using connection ID '***' for task execution.
[2023-09-28T17:43:32.469+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers_manager.py:669: DeprecationWarning: The provider apache-***-providers-docker uses `hook-class-names` property in provider-info and has no `connection-types` one. The 'hook-class-names' property has been deprecated in favour of 'connection-types' in Airflow 2.2. Use **both** in case you want to have backwards compatibility with Airflow < 2.2
  warnings.warn(

[2023-09-28T17:43:32.483+0000] {base.py:73} INFO - Using connection ID '***' for task execution.
[2023-09-28T17:45:43.268+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/common/sql/operators/sql.py", line 271, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 341, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/postgres/hooks/postgres.py", line 144, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "172.27.70.244", port 5434 failed: Connection timed out
	Is the server running on that host and accepting TCP/IP connections?

[2023-09-28T17:45:43.292+0000] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=user_processing, task_id=set_search_path, execution_date=20230927T000000, start_date=20230928T174331, end_date=20230928T174543
[2023-09-28T17:45:43.320+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 319 for task set_search_path (connection to server at "172.27.70.244", port 5434 failed: Connection timed out
	Is the server running on that host and accepting TCP/IP connections?
; 74)
[2023-09-28T17:45:43.344+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-09-28T17:45:43.366+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
