[2023-10-08T00:00:08.017+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_processing.set_search_path scheduled__2023-10-07T00:00:00+00:00 [queued]>
[2023-10-08T00:00:08.081+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_processing.set_search_path scheduled__2023-10-07T00:00:00+00:00 [queued]>
[2023-10-08T00:00:08.082+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-10-08T00:00:08.414+0000] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): set_search_path> on 2023-10-07 00:00:00+00:00
[2023-10-08T00:00:08.440+0000] {standard_task_runner.py:57} INFO - Started process 739 to run task
[2023-10-08T00:00:08.500+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'set_search_path', 'scheduled__2023-10-07T00:00:00+00:00', '--job-id', '654', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpqxeci6bi']
[2023-10-08T00:00:08.559+0000] {standard_task_runner.py:85} INFO - Job 654: Subtask set_search_path
[2023-10-08T00:00:08.879+0000] {task_command.py:410} INFO - Running <TaskInstance: user_processing.set_search_path scheduled__2023-10-07T00:00:00+00:00 [running]> on host 3c74e60f688b
[2023-10-08T00:00:09.256+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='user_processing' AIRFLOW_CTX_TASK_ID='set_search_path' AIRFLOW_CTX_EXECUTION_DATE='2023-10-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-07T00:00:00+00:00'
[2023-10-08T00:00:09.257+0000] {sql.py:265} INFO - Executing: SET search_path TO ***_ini
[2023-10-08T00:00:09.283+0000] {base.py:73} INFO - Using connection ID '***' for task execution.
[2023-10-08T00:00:09.681+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.10/site-packages/***/providers_manager.py:669: DeprecationWarning: The provider apache-***-providers-docker uses `hook-class-names` property in provider-info and has no `connection-types` one. The 'hook-class-names' property has been deprecated in favour of 'connection-types' in Airflow 2.2. Use **both** in case you want to have backwards compatibility with Airflow < 2.2
  warnings.warn(

[2023-10-08T00:00:09.696+0000] {base.py:73} INFO - Using connection ID '***' for task execution.
[2023-10-08T00:02:23.652+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/common/sql/operators/sql.py", line 271, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/common/sql/hooks/sql.py", line 341, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/postgres/hooks/postgres.py", line 144, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "172.27.70.244", port 5434 failed: Connection timed out
	Is the server running on that host and accepting TCP/IP connections?

[2023-10-08T00:02:23.664+0000] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=user_processing, task_id=set_search_path, execution_date=20231007T000000, start_date=20231008T000008, end_date=20231008T000223
[2023-10-08T00:02:23.684+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 654 for task set_search_path (connection to server at "172.27.70.244", port 5434 failed: Connection timed out
	Is the server running on that host and accepting TCP/IP connections?
; 739)
[2023-10-08T00:02:23.734+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-10-08T00:02:23.769+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
